/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package database_project;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Shannu
 */
public class ADMIN_HOMEPAGE_GUI extends javax.swing.JFrame {

     public boolean database;
    private void GetData(){ 
        try {
            Connection conn =(Connection)database_project.Connection_DB.DBCon();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("select * from CUSTOMER");
            Display_Table.setModel(DbUtils.resultSetToTableModel(sql));
        } 
        catch (SQLException | HeadlessException e) {
        }
    }
    public ADMIN_HOMEPAGE_GUI() {
        initComponents();
        setTitle("Admin Homepage");
        GetData();
        database=true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Display_Table = new javax.swing.JTable();
        Musicians = new javax.swing.JButton();
        Album_Producer = new javax.swing.JButton();
        Instruments = new javax.swing.JButton();
        Lives = new javax.swing.JButton();
        Perform = new javax.swing.JButton();
        Places = new javax.swing.JButton();
        Plays = new javax.swing.JButton();
        Songs_Appears = new javax.swing.JButton();
        Telephone_Home = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Exit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Display_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NAME", "ALBUM TITLE", "SONG"
            }
        ));
        Display_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Display_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Display_Table);

        Musicians.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        Musicians.setText("Musicians");
        Musicians.setPreferredSize(new java.awt.Dimension(113, 23));
        Musicians.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MusiciansActionPerformed(evt);
            }
        });

        Album_Producer.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        Album_Producer.setText("Album Producer");
        Album_Producer.setPreferredSize(new java.awt.Dimension(113, 23));
        Album_Producer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Album_ProducerActionPerformed(evt);
            }
        });

        Instruments.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        Instruments.setText("Instruments");
        Instruments.setPreferredSize(new java.awt.Dimension(113, 23));
        Instruments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstrumentsActionPerformed(evt);
            }
        });

        Lives.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        Lives.setText("Lives");
        Lives.setPreferredSize(new java.awt.Dimension(113, 23));
        Lives.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LivesActionPerformed(evt);
            }
        });

        Perform.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        Perform.setText("Perform");
        Perform.setPreferredSize(new java.awt.Dimension(113, 23));
        Perform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerformActionPerformed(evt);
            }
        });

        Places.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        Places.setText("Places");
        Places.setPreferredSize(new java.awt.Dimension(113, 23));
        Places.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlacesActionPerformed(evt);
            }
        });

        Plays.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        Plays.setText("Plays");
        Plays.setPreferredSize(new java.awt.Dimension(113, 23));
        Plays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlaysActionPerformed(evt);
            }
        });

        Songs_Appears.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        Songs_Appears.setText("Songs Appears");
        Songs_Appears.setPreferredSize(new java.awt.Dimension(113, 23));
        Songs_Appears.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Songs_AppearsActionPerformed(evt);
            }
        });

        Telephone_Home.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        Telephone_Home.setText("Telephone Home");
        Telephone_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Telephone_HomeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel1.setText("                        Notown Music Records Administrative Page");

        Exit.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel2.setText("Click on the table that you would like to acces:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(Musicians, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addComponent(Album_Producer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Instruments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Plays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Perform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Places, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lives, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(97, 97, 97)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Songs_Appears, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Telephone_Home)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(Exit)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Musicians, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Album_Producer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Instruments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Places, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Plays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Songs_Appears, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Perform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Telephone_Home)
                    .addComponent(Lives, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(Exit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Display_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Display_TableMouseClicked
        database = false;
        try {
           int row =Display_Table.getSelectedRow();
            String table=(Display_Table.getModel().getValueAt(row, 0).toString());
            java.sql.Connection conn =(java.sql.Connection)database_project.Connection_DB.DBCon();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("select * from CUSTOMER");
            
       } catch (Exception e) {
       }
    }//GEN-LAST:event_Display_TableMouseClicked

    private void MusiciansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MusiciansActionPerformed
        MUSICIANS_GUI musicians=new MUSICIANS_GUI();
        musicians.setVisible(true);
    }//GEN-LAST:event_MusiciansActionPerformed

    private void Album_ProducerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Album_ProducerActionPerformed
        ALBUM_PRODUCER_GUI albumproducer=new ALBUM_PRODUCER_GUI();
        albumproducer.setVisible(true);
    }//GEN-LAST:event_Album_ProducerActionPerformed

    private void InstrumentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstrumentsActionPerformed
        INSTRUMENTS_GUI instruments=new INSTRUMENTS_GUI();
        instruments.setVisible(true);
    }//GEN-LAST:event_InstrumentsActionPerformed

    private void LivesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LivesActionPerformed
        LIVES_GUI lives=new LIVES_GUI();
        lives.setVisible(true);
    }//GEN-LAST:event_LivesActionPerformed

    private void PerformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerformActionPerformed
        PERFORM_GUI perform=new PERFORM_GUI();
        perform.setVisible(true);
    }//GEN-LAST:event_PerformActionPerformed

    private void PlacesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlacesActionPerformed
        PLACES_GUI places=new PLACES_GUI();
        places.setVisible(true);
    }//GEN-LAST:event_PlacesActionPerformed

    private void PlaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlaysActionPerformed
        PLAYS_GUI plays=new PLAYS_GUI();
        plays.setVisible(true);
    }//GEN-LAST:event_PlaysActionPerformed

    private void Songs_AppearsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Songs_AppearsActionPerformed
        SONGS_APPEARS_GUI songsappears=new SONGS_APPEARS_GUI();
        songsappears.setVisible(true);
    }//GEN-LAST:event_Songs_AppearsActionPerformed

    private void Telephone_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Telephone_HomeActionPerformed
        TELEPHONE_HOME_GUI telephonehome=new TELEPHONE_HOME_GUI();
        telephonehome.setVisible(true);
    }//GEN-LAST:event_Telephone_HomeActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        if (evt.getSource() == Exit) {
           
            dispose();
        }
    }//GEN-LAST:event_ExitActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADMIN_HOMEPAGE_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADMIN_HOMEPAGE_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADMIN_HOMEPAGE_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADMIN_HOMEPAGE_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADMIN_HOMEPAGE_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Album_Producer;
    private javax.swing.JTable Display_Table;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Instruments;
    private javax.swing.JButton Lives;
    private javax.swing.JButton Musicians;
    private javax.swing.JButton Perform;
    private javax.swing.JButton Places;
    private javax.swing.JButton Plays;
    private javax.swing.JButton Songs_Appears;
    private javax.swing.JButton Telephone_Home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
